### ISSUE TITLE
Cant install from npm

### ISSUE THREAD

**Issue by krylincy-zz** [boblauer/jQasper#1]
When i try to install with "npm install jQasper" i get this error:

npm ERR! 404 'jQasper' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

can u please fix it?

**Comment by boblauer** [comment]
My mistake, it should be npm install jqasper.  All npm modules must have all lower-case names.  I have fixed the README as well.  Sorry about that!

**Comment by krylincy-zz** [comment]
Big Thanks!!
